import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Praticando React',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<div className={'w-full flex justify-center pt-5'}>
					<Link href={'/'}>
						<h1
							className={
								'text-center font-bold text-4xl text-blue-600'
							}
						>
							Praticando React ⚛️
						</h1>
					</Link>
				</div>

				{children}
			</body>
		</html>
	);
}
